### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by colmaengus** [Haivision/srt#893]
I'm seeing a problem where CPU usage goes up to 100% for sender srt-live-transmit as soon as the sender and receiver connect.
I'm using docker to create two containers, one for sender, one for receiver (see below for details)
I'm using latest from master as of 30-Sept-2019.

**Dockerfile**

```
FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get upgrade --no-install-recommends -y software-properties-common tclsh pkg-config cmake libssl-dev build-essential \
    && rm -rf /var/lib/apt/lists/*
```

**docker-compose.yaml**
```
version: '2'
services:
  sender:
    image: srt-dev
    working_dir: /usr/src/srt
    volumes:
      - ../srt:/usr/src/srt
    command: bash -c "tail -f /dev/null"
  receiver:
    image: srt-dev
    working_dir: /usr/src/srt
    volumes:
      - ../srt:/usr/src/srt
    command: bash -c "tail -f /dev/null"
```
After building srt-dev and starting the stack I shell into each container and run the following
**receiver**
`./srt-live-transmit srt://:8000 udp://host.docker.internal:9002`

**sender**
`./srt-live-transmit udp://localhost:9000 srt://receiver:8000`

As soon as they connect the sender container cpu goes up to 100%.
The full setup includes sending a udp stream from ffmpeg to the sender and connecting ffplay to the receiver but they don't have an impact on the high CPU.
